### ISSUE TITLE
Message

### ISSUE THREAD

**Issue by nicholasshirley** [nicholasshirley/DTA-Vue-Rails#1]
@mattsketchy I didn't want to say anything negative on that old issue and I don't see an email on your profile, but if you are using that gem in production, you are setting yourself up for a world of pain. I've tried to deploy it in 2 apps and it's nothing but trouble. By the time you overwrite all the controllers to use it like a proper API token auth you could have just done it yourself. Not to mention that token switching on request doesn't work at all which kills pretty much any reason to use it. Take a look at [knock_once](https://github.com/nicholasshirley/knock_once) It's a little side project I put together. I _would not_ recommend using that in production either, but I think you'll see there isn't that much to it if you are running Rails as an API.

Just wanted to tell you, I have a lot of wasted hours messing with it.

**Comment by mattsketchy** [comment]
@nicholasshirley thanks a ton for reaching out on this message - interesting you had that experience. I will proceed with caution and check out your side project as well. Good luck with your projects going forward. Happy coding!
